### ISSUE TITLE
Typescript module and type declaration error

### ISSUE THREAD

**Issue by mak12** [surveysparrow/surveysparrow-react-native-sdk#9]
Getting warning of module and type declarations in typescript file

Environment details:
`"react-native": "0.68.1",`

<img width="744" alt="Screenshot 2022-10-12 at 3 23 12 PM" src="https://user-images.githubusercontent.com/30626811/195318842-db2fbdf1-427c-475f-97cf-0ff2cba787ec.png">

**Comment by EgorZotov** [comment]
I think the issue is module suffix resolution by typescript.
Basically this module exports type for every platform like so:
<img width="318" alt="Screenshot 2022-10-17 at 3 26 05 PM" src="https://user-images.githubusercontent.com/23280344/196165424-c3353c38-292a-476b-9c46-50debe3c237b.png">

Not every project's `tsconfig.json` supports this export configuration.
If your typescript version >4.7 you can use included module resolution option. Just add this:
```json
"compilerOptions": {
  ...
  "moduleSuffixes": [".ios", ".android", ""],
}
```

This should resolve ts errors but i think there is some space to better type this module but I don't have time to dig.

**Comment by sachin-kumar56** [comment]
@EgorZotov thanks for the reply @mak12 hope @EgorZotov answer fixed your issue, we are working on updating the SDK to a newer version, and in that, we will address the typing issue
